"""
Great pack of pygame keyboard events constansts packed into object.
"""
import os

__all__ = ['key_flags', 'K', 'KEY']

_pygame_constants = {
    'K_0': 48, 'K_1': 49, 'K_2': 50, 'K_3': 51, 'K_4': 52, 'K_5': 53, 'K_6': 54, 'K_7': 55, 'K_8': 56, 'K_9': 57, 'K_a': 97,
    'K_AC_BACK': 1073742094, 'K_AMPERSAND': 38, 'K_ASTERISK': 42, 'K_AT': 64, 'K_b': 98, 'K_BACKQUOTE': 96, 'K_BACKSLASH': 92,
    'K_BACKSPACE': 8, 'K_BREAK': 1073741896, 'K_c': 99, 'K_CAPSLOCK': 1073741881, 'K_CARET': 94, 'K_CLEAR': 1073741980, 'K_COLON': 58,
    'K_COMMA': 44, 'K_CURRENCYSUBUNIT': 1073742005, 'K_CURRENCYUNIT': 1073742004, 'K_d': 100, 'K_DELETE': 127, 'K_DOLLAR': 36,
    'K_DOWN': 1073741905, 'K_e': 101, 'K_END': 1073741901, 'K_EQUALS': 61, 'K_ESCAPE': 27, 'K_EURO': 1073742004, 'K_EXCLAIM': 33, 'K_f': 102,
    'K_F1': 1073741882, 'K_F10': 1073741891, 'K_F11': 1073741892, 'K_F12': 1073741893, 'K_F13': 1073741928, 'K_F14': 1073741929,
    'K_F15': 1073741930, 'K_F2': 1073741883, 'K_F3': 1073741884, 'K_F4': 1073741885, 'K_F5': 1073741886, 'K_F6': 1073741887,
    'K_F7': 1073741888, 'K_F8': 1073741889, 'K_F9': 1073741890, 'K_g': 103, 'K_GREATER': 62, 'K_h': 104, 'K_HASH': 35, 'K_HELP': 1073741941,
    'K_HOME': 1073741898, 'K_i': 105, 'K_INSERT': 1073741897, 'K_j': 106, 'K_k': 107, 'K_KP0': 1073741922, 'K_KP1': 1073741913,
    'K_KP2': 1073741914, 'K_KP3': 1073741915, 'K_KP4': 1073741916, 'K_KP5': 1073741917, 'K_KP6': 1073741918, 'K_KP7': 1073741919,
    'K_KP8': 1073741920, 'K_KP9': 1073741921, 'K_KP_0': 1073741922, 'K_KP_1': 1073741913, 'K_KP_2': 1073741914, 'K_KP_3': 1073741915,
    'K_KP_4': 1073741916, 'K_KP_5': 1073741917, 'K_KP_6': 1073741918, 'K_KP_7': 1073741919, 'K_KP_8': 1073741920, 'K_KP_9': 1073741921,
    'K_KP_DIVIDE': 1073741908, 'K_KP_ENTER': 1073741912, 'K_KP_EQUALS': 1073741927, 'K_KP_MINUS': 1073741910, 'K_KP_MULTIPLY': 1073741909,
    'K_KP_PERIOD': 1073741923, 'K_KP_PLUS': 1073741911, 'K_l': 108, 'K_LALT': 1073742050, 'K_LCTRL': 1073742048, 'K_LEFT': 1073741904,
    'K_LEFTBRACKET': 91, 'K_LEFTPAREN': 40, 'K_LESS': 60, 'K_LGUI': 1073742051, 'K_LMETA': 1073742051, 'K_LSHIFT': 1073742049,
    'K_LSUPER': 1073742051, 'K_m': 109, 'K_MENU': 1073741942, 'K_MINUS': 45, 'K_MODE': 1073742081, 'K_n': 110, 'K_NUMLOCK': 1073741907,
    'K_NUMLOCKCLEAR': 1073741907, 'K_o': 111, 'K_p': 112, 'K_PAGEDOWN': 1073741902, 'K_PAGEUP': 1073741899, 'K_PAUSE': 1073741896,
    'K_PERCENT': 37, 'K_PERIOD': 46, 'K_PLUS': 43, 'K_POWER': 1073741926, 'K_PRINT': 1073741894, 'K_PRINTSCREEN': 1073741894, 'K_q': 113,
    'K_QUESTION': 63, 'K_QUOTE': 39, 'K_QUOTEDBL': 34, 'K_r': 114, 'K_RALT': 1073742054, 'K_RCTRL': 1073742052, 'K_RETURN': 13,
    'K_RGUI': 1073742055, 'K_RIGHT': 1073741903, 'K_RIGHTBRACKET': 93, 'K_RIGHTPAREN': 41, 'K_RMETA': 1073742055, 'K_RSHIFT': 1073742053,
    'K_RSUPER': 1073742055, 'K_s': 115, 'K_SCROLLLOCK': 1073741895, 'K_SCROLLOCK': 1073741895, 'K_SEMICOLON': 59, 'K_SLASH': 47, 'K_SPACE': 32,
    'K_SYSREQ': 1073741978, 'K_t': 116, 'K_TAB': 9, 'K_u': 117, 'K_UNDERSCORE': 95, 'K_UNKNOWN': 0, 'K_UP': 1073741906, 'K_v': 118, 'K_w': 119,
    'K_x': 120, 'K_y': 121, 'K_z': 122, 'KMOD_ALT': 768, 'KMOD_CAPS': 8192, 'KMOD_CTRL': 192, 'KMOD_GUI': 3072, 'KMOD_LALT': 256,
    'KMOD_LCTRL': 64, 'KMOD_LGUI': 1024, 'KMOD_LMETA': 1024, 'KMOD_LSHIFT': 1, 'KMOD_META': 3072, 'KMOD_MODE': 16384, 'KMOD_NONE': 0,
    'KMOD_NUM': 4096, 'KMOD_RALT': 512, 'KMOD_RCTRL': 128, 'KMOD_RGUI': 2048, 'KMOD_RMETA': 2048, 'KMOD_RSHIFT': 2, 'KMOD_SHIFT': 3,
}

# TODO Check if GUI is possible
if not bool(os.environ.get('EJUDGE_MODE', False)):
    try:
        import pygame.constants
        _pygame_constants.update({getattr(pygame.constants, name) for name in dir(pygame.constants)})
    except Exception as e:
        # In console mode pygame is not needed. So we use just some constants, actually taken from pygame.constants
        pass


class KeyFlags:
    MOD_ALT = _pygame_constants['KMOD_ALT']
    MOD_CAPS = _pygame_constants['KMOD_CAPS']
    MOD_CTRL = _pygame_constants['KMOD_CTRL']
    MOD_GUI = _pygame_constants['KMOD_GUI']
    MOD_LALT = _pygame_constants['KMOD_LALT']
    MOD_LCTRL = _pygame_constants['KMOD_LCTRL']
    MOD_LGUI = _pygame_constants['KMOD_LGUI']
    MOD_LMETA = _pygame_constants['KMOD_LMETA']
    MOD_LSHIFT = _pygame_constants['KMOD_LSHIFT']
    MOD_META = _pygame_constants['KMOD_META']
    MOD_MODE = _pygame_constants['KMOD_MODE']
    MOD_NONE = _pygame_constants['KMOD_NONE']
    MOD_NUM = _pygame_constants['KMOD_NUM']
    MOD_RALT = _pygame_constants['KMOD_RALT']
    MOD_RCTRL = _pygame_constants['KMOD_RCTRL']
    MOD_RGUI = _pygame_constants['KMOD_RGUI']
    MOD_RMETA = _pygame_constants['KMOD_RMETA']
    MOD_RSHIFT = _pygame_constants['KMOD_RSHIFT']
    MOD_SHIFT = _pygame_constants['KMOD_SHIFT']
    K_0 = _pygame_constants['K_0']
    K_1 = _pygame_constants['K_1']
    K_2 = _pygame_constants['K_2']
    K_3 = _pygame_constants['K_3']
    K_4 = _pygame_constants['K_4']
    K_5 = _pygame_constants['K_5']
    K_6 = _pygame_constants['K_6']
    K_7 = _pygame_constants['K_7']
    K_8 = _pygame_constants['K_8']
    K_9 = _pygame_constants['K_9']
    _0 = _pygame_constants['K_0']
    _1 = _pygame_constants['K_1']
    _2 = _pygame_constants['K_2']
    _3 = _pygame_constants['K_3']
    _4 = _pygame_constants['K_4']
    _5 = _pygame_constants['K_5']
    _6 = _pygame_constants['K_6']
    _7 = _pygame_constants['K_7']
    _8 = _pygame_constants['K_8']
    _9 = _pygame_constants['K_9']
    AC_BACK = _pygame_constants['K_AC_BACK']
    AMPERSAND = _pygame_constants['K_AMPERSAND']
    ASTERISK = _pygame_constants['K_ASTERISK']
    AT = _pygame_constants['K_AT']
    BACKQUOTE = _pygame_constants['K_BACKQUOTE']
    BACKSLASH = _pygame_constants['K_BACKSLASH']
    BACKSPACE = _pygame_constants['K_BACKSPACE']
    BREAK = _pygame_constants['K_BREAK']
    CAPSLOCK = _pygame_constants['K_CAPSLOCK']
    CARET = _pygame_constants['K_CARET']
    CLEAR = _pygame_constants['K_CLEAR']
    COLON = _pygame_constants['K_COLON']
    COMMA = _pygame_constants['K_COMMA']
    CURRENCYSUBUNIT = _pygame_constants['K_CURRENCYSUBUNIT']
    CURRENCYUNIT = _pygame_constants['K_CURRENCYUNIT']
    DELETE = _pygame_constants['K_DELETE']
    DOLLAR = _pygame_constants['K_DOLLAR']
    DOWN = _pygame_constants['K_DOWN']
    END = _pygame_constants['K_END']
    EQUALS = _pygame_constants['K_EQUALS']
    ESCAPE = _pygame_constants['K_ESCAPE']
    EURO = _pygame_constants['K_EURO']
    EXCLAIM = _pygame_constants['K_EXCLAIM']
    F1 = _pygame_constants['K_F1']
    F10 = _pygame_constants['K_F10']
    F11 = _pygame_constants['K_F11']
    F12 = _pygame_constants['K_F12']
    F13 = _pygame_constants['K_F13']
    F14 = _pygame_constants['K_F14']
    F15 = _pygame_constants['K_F15']
    F2 = _pygame_constants['K_F2']
    F3 = _pygame_constants['K_F3']
    F4 = _pygame_constants['K_F4']
    F5 = _pygame_constants['K_F5']
    F6 = _pygame_constants['K_F6']
    F7 = _pygame_constants['K_F7']
    F8 = _pygame_constants['K_F8']
    F9 = _pygame_constants['K_F9']
    GREATER = _pygame_constants['K_GREATER']
    HASH = _pygame_constants['K_HASH']
    HELP = _pygame_constants['K_HELP']
    HOME = _pygame_constants['K_HOME']
    INSERT = _pygame_constants['K_INSERT']
    KP0 = _pygame_constants['K_KP0']
    KP1 = _pygame_constants['K_KP1']
    KP2 = _pygame_constants['K_KP2']
    KP3 = _pygame_constants['K_KP3']
    KP4 = _pygame_constants['K_KP4']
    KP5 = _pygame_constants['K_KP5']
    KP6 = _pygame_constants['K_KP6']
    KP7 = _pygame_constants['K_KP7']
    KP8 = _pygame_constants['K_KP8']
    KP9 = _pygame_constants['K_KP9']
    KP_0 = _pygame_constants['K_KP_0']
    KP_1 = _pygame_constants['K_KP_1']
    KP_2 = _pygame_constants['K_KP_2']
    KP_3 = _pygame_constants['K_KP_3']
    KP_4 = _pygame_constants['K_KP_4']
    KP_5 = _pygame_constants['K_KP_5']
    KP_6 = _pygame_constants['K_KP_6']
    KP_7 = _pygame_constants['K_KP_7']
    KP_8 = _pygame_constants['K_KP_8']
    KP_9 = _pygame_constants['K_KP_9']
    KP_DIVIDE = _pygame_constants['K_KP_DIVIDE']
    KP_ENTER = _pygame_constants['K_KP_ENTER']
    KP_EQUALS = _pygame_constants['K_KP_EQUALS']
    KP_MINUS = _pygame_constants['K_KP_MINUS']
    KP_MULTIPLY = _pygame_constants['K_KP_MULTIPLY']
    KP_PERIOD = _pygame_constants['K_KP_PERIOD']
    KP_PLUS = _pygame_constants['K_KP_PLUS']
    LALT = _pygame_constants['K_LALT']
    LCTRL = _pygame_constants['K_LCTRL']
    LEFT = _pygame_constants['K_LEFT']
    LEFTBRACKET = _pygame_constants['K_LEFTBRACKET']
    LEFTPAREN = _pygame_constants['K_LEFTPAREN']
    LESS = _pygame_constants['K_LESS']
    LGUI = _pygame_constants['K_LGUI']
    LMETA = _pygame_constants['K_LMETA']
    LSHIFT = _pygame_constants['K_LSHIFT']
    LSUPER = _pygame_constants['K_LSUPER']
    MENU = _pygame_constants['K_MENU']
    MINUS = _pygame_constants['K_MINUS']
    MODE = _pygame_constants['K_MODE']
    NUMLOCK = _pygame_constants['K_NUMLOCK']
    NUMLOCKCLEAR = _pygame_constants['K_NUMLOCKCLEAR']
    PAGEDOWN = _pygame_constants['K_PAGEDOWN']
    PAGEUP = _pygame_constants['K_PAGEUP']
    PAUSE = _pygame_constants['K_PAUSE']
    PERCENT = _pygame_constants['K_PERCENT']
    PERIOD = _pygame_constants['K_PERIOD']
    PLUS = _pygame_constants['K_PLUS']
    POWER = _pygame_constants['K_POWER']
    PRINT = _pygame_constants['K_PRINT']
    PRINTSCREEN = _pygame_constants['K_PRINTSCREEN']
    QUESTION = _pygame_constants['K_QUESTION']
    QUOTE = _pygame_constants['K_QUOTE']
    QUOTEDBL = _pygame_constants['K_QUOTEDBL']
    RALT = _pygame_constants['K_RALT']
    RCTRL = _pygame_constants['K_RCTRL']
    RETURN = _pygame_constants['K_RETURN']
    RGUI = _pygame_constants['K_RGUI']
    RIGHT = _pygame_constants['K_RIGHT']
    RIGHTBRACKET = _pygame_constants['K_RIGHTBRACKET']
    RIGHTPAREN = _pygame_constants['K_RIGHTPAREN']
    RMETA = _pygame_constants['K_RMETA']
    RSHIFT = _pygame_constants['K_RSHIFT']
    RSUPER = _pygame_constants['K_RSUPER']
    SCROLLLOCK = _pygame_constants['K_SCROLLLOCK']
    SCROLLOCK = _pygame_constants['K_SCROLLOCK']
    SEMICOLON = _pygame_constants['K_SEMICOLON']
    SLASH = _pygame_constants['K_SLASH']
    SPACE = _pygame_constants['K_SPACE']
    SYSREQ = _pygame_constants['K_SYSREQ']
    TAB = _pygame_constants['K_TAB']
    UNDERSCORE = _pygame_constants['K_UNDERSCORE']
    UNKNOWN = _pygame_constants['K_UNKNOWN']
    UP = _pygame_constants['K_UP']
    a = _pygame_constants['K_a']
    b = _pygame_constants['K_b']
    c = _pygame_constants['K_c']
    d = _pygame_constants['K_d']
    e = _pygame_constants['K_e']
    f = _pygame_constants['K_f']
    g = _pygame_constants['K_g']
    h = _pygame_constants['K_h']
    i = _pygame_constants['K_i']
    j = _pygame_constants['K_j']
    k = _pygame_constants['K_k']
    l = _pygame_constants['K_l']
    m = _pygame_constants['K_m']
    n = _pygame_constants['K_n']
    o = _pygame_constants['K_o']
    p = _pygame_constants['K_p']
    q = _pygame_constants['K_q']
    r = _pygame_constants['K_r']
    s = _pygame_constants['K_s']
    t = _pygame_constants['K_t']
    u = _pygame_constants['K_u']
    v = _pygame_constants['K_v']
    w = _pygame_constants['K_w']
    x = _pygame_constants['K_x']
    y = _pygame_constants['K_y']
    z = _pygame_constants['K_z']
    A = _pygame_constants['K_a']
    B = _pygame_constants['K_b']
    C = _pygame_constants['K_c']
    D = _pygame_constants['K_d']
    E = _pygame_constants['K_e']
    F = _pygame_constants['K_f']
    G = _pygame_constants['K_g']
    H = _pygame_constants['K_h']
    I = _pygame_constants['K_i']
    J = _pygame_constants['K_j']
    K = _pygame_constants['K_k']
    L = _pygame_constants['K_l']
    M = _pygame_constants['K_m']
    N = _pygame_constants['K_n']
    O = _pygame_constants['K_o']
    P = _pygame_constants['K_p']
    Q = _pygame_constants['K_q']
    R = _pygame_constants['K_r']
    S = _pygame_constants['K_s']
    T = _pygame_constants['K_t']
    U = _pygame_constants['K_u']
    V = _pygame_constants['K_v']
    W = _pygame_constants['K_w']
    X = _pygame_constants['K_x']
    Y = _pygame_constants['K_y']
    Z = _pygame_constants['K_z']

    def __str__(self):
        print([f'K.{c}' for c in dir(self) if not c.startswith('__')])


K = KEY = key_flags = KeyFlags()
